defaults: &defaults
  working_directory: ~/build
  docker:
    - image: docker:git
    
version: 2
jobs:
  install_dependencies:
    <<: *defaults
    steps:

      - checkout

      - setup_remote_docker:
          reusable: true
          exclusive: true

      - run:
          name: INSTALL DEPENDENCIES
          command: |
            apk add --update py-pip
            python -m pip install --upgrade pip
            pip install --upgrade requests
          
      - persist_to_workspace:
          root: ~/build
          paths:
            - .
 
  staging:
    <<: *defaults
    steps:
      - attach_workspace:
          at: workspace/
          
      - run:
          name: TEST - staging
          command: |
            ls -la workspace/
      
  staging-e2e:
    <<: *defaults
    steps:
      - attach_workspace:
          at: workspace/
          
      - run:
          name: TEST - staging-e2e
          command: |
            ls -la workspace/
      
  production:
    <<: *defaults
    steps:
      - attach_workspace:
          at: workspace/
          
      - run:
          name: TEST - production
          command: |
            ls -la workspace/

workflows:
  version: 2

  continuous-delivery-workflow:
    jobs:
      - install_dependencies:
        filters:
          tags:
            only: /.*/
          branches:
            only: /.*/

      - staging:
          requires:
            - install_dependencies

      - staging-e2e:
          requires:
            - staging

      - approve-production:
          type: approval
          requires:
            - staging-e2e

      - production:
          requires:
            - approve-production
